name: Bitcoin Signal Analysis

on:
  schedule:
    # Run every 4 hours (0, 4, 8, 12, 16, 20 UTC)
    - cron: '0 */4 * * *'
  workflow_dispatch: # Allow manual runs

jobs:
  analyze:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run Bitcoin Analysis
      env:
        TAVILY_API_KEY: ${{ secrets.TAVILY_API_KEY }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        SMTP_USER: ${{ secrets.SMTP_USER }}
        SMTP_PASS: ${{ secrets.SMTP_PASS }}
        SMTP_TO: ${{ secrets.SMTP_TO }}
      run: |
        python AlphaCrypto.py
        
    - name: Upload results
      uses: actions/upload-artifact@v4
      with:
        name: bitcoin-analysis-results
        path: |
          signal.json
          report.md
          features.csv
          audit.log