name: Order Book Microstructure Analysis

on:
  schedule:
    # Run every 5 minutes for data collection and analysis
    - cron: '*/5 * * * *'
  workflow_dispatch: # Allow manual runs
  push:
    branches: [ main ]
    paths:
      - 'src/AlphaCrypto_OrderBook.py'
      - '.github/workflows/orderbook-collection.yml'

jobs:
  collect-orderbook-data:
    runs-on: ubuntu-latest
    timeout-minutes: 5  # Prevent long-running jobs
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Create data directories
      run: |
        mkdir -p data/raw data/processed data/outputs/reports data/outputs/logs data/archive
        
    - name: Run Order Book Analysis
      run: |
        python src/AlphaCrypto_OrderBook.py
        
    - name: Upload Order Book Data
      uses: actions/upload-artifact@v4
      with:
        name: orderbook-data-${{ github.run_number }}
        path: |
          data/raw/orderbook_data.csv
          data/raw/trades_data.csv
          data/processed/orderbook_features.csv
          data/outputs/orderbook_signals.json
          data/outputs/reports/orderbook_report.md
        retention-days: 30  # Keep artifacts for 30 days
        
    - name: Upload Logs
      uses: actions/upload-artifact@v4
      with:
        name: orderbook-logs-${{ github.run_number }}
        path: |
          data/outputs/logs/
        retention-days: 7  # Keep logs for 7 days

  continuous-collection:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'  # Only run on manual trigger
    timeout-minutes: 60  # Allow longer runs for continuous collection
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Create data directories
      run: |
        mkdir -p data/raw data/processed data/outputs/reports data/outputs/logs data/archive
        
    - name: Run Continuous Order Book Collection
      run: |
        timeout 45m python src/AlphaCrypto_OrderBook.py --continuous
        
    - name: Upload Continuous Collection Data
      uses: actions/upload-artifact@v4
      with:
        name: continuous-orderbook-data-${{ github.run_number }}
        path: |
          data/raw/
          data/processed/
          data/outputs/
        retention-days: 7